### ISSUE TITLE
table doesn't load with new itemsperpage

### ISSUE THREAD

**Issue by rohansp** [Zizzamia/ng-tasty#101]
I have created a dropdown and binded to model gridpagination.count
```js
return $http.get(urlApi).then(function (response) {
            $scope.gridpagination = response.data.pagination;
            return {
                'rows': response.data.rows,
                'header': response.data.header,
                'pagination': $scope.gridpagination,
                'sortby': response.data.sortby,
                'sortorder': response.data.sortorder
            }
});
```
I get the required data from the server, however the items per page doesnt bind to the table.
So initially if I have 10 records per page and I select 25 from dropdown, it still shows 10 records per page.Whereas, when I check the Json returned from the server,it shows 25 records per page..
What could be the issue?

**Comment by rohansp** [comment]
Also, one more point , when I use the square buttons ie listItemsPerPage [10,25,50,100] for Pagination the grid loads with correct no of records.

**Comment by Zizzamia** [comment]
The implementation above is not correct, if you can copy and paste all your html and js will be easier help you.

**Comment by rohansp** [comment]
--app.js
var app = angular.module("MyApp", ['ngTasty']);


app.controller("PaginationCtrl", function ($scope, $http) {

    $scope.init = {
        'count': 10,
        'page': 1,
        'sortBy': 'CustomerId',
        'sortOrder': 'asc',
        'listItemsPerPage': [10, 25, 50, 100],
        'itemsPerPage': 10,
        'pagination': true
    };

    $scope.listItemsPerPage = [10, 25, 50, 100];

    $scope.reloadCallBack = function (params, paramsObj, isreload, value) {
        $scope.getResource(params, paramsObj, isreload, value);
    }


    var gridparams;
    var gridparamsObj;
    $scope.getResource = function (params, paramsObj, isreload, value) {
        if (isreload == true) {
            params = gridparams;
            paramsObj = gridparamsObj;
            paramsObj.count = parseInt($scope.gridpagination.count);
        }
        else {
            gridparams = params;
            gridparamsObj = paramsObj;
        }

        var pageno = paramsObj.page;
        var records = paramsObj.count;
        var urlApi = 'Service1.svc/GetCustomer?pageno=' + pageno + "&records=" + records;
        return $http.get(urlApi).then(function (response) {
            $scope.gridpagination = response.data.pagination;
            console.log($scope.gridpagination);
            return {
                'rows': response.data.rows,
                'header': response.data.header,
                'pagination': $scope.gridpagination,
                'sortby': response.data.sortby,
                'sortorder': response.data.sortorder
            }
        });
    }



});

--DataGridNew.html
<html>
  <head>
  <link href="bootstrap.min.css" rel="Stylesheet"/>
    <script src="angular.js"></script>    
	<script src="app.js"></script>
    <script src="ng-tasty-tpls.min.js"></script>
  </head>
  <body ng-app="MyApp">
    <div ng-controller="PaginationCtrl">
      <div tasty-table bind-resource-callback="getResource" data-bind-init="init">
		  <table class="table table-striped table-condensed">
			<thead>
			  <tr>
				<th>Customer Id</th>
				<th>Name</th>
				<th>Country</th>
			  </tr>
			<thead>
			<tbody>
			  <tr ng-repeat="row in rows">
				<td>{{ row.CustomerId }}</td>
				<td>{{ row.Name }}</td>
				<td>{{ row.Country }}</td>
			  </tr>
			</tbody>
		  </table>
		  <div tasty-pagination bind-list-items-per-page="listItemsPerPage" bind-items-per-page="itemsPerPage" >
         
          </div>
          <select ng-model="gridpagination.count" ng-change="getResource('','',true,this)">
          <option>10</option>
          <option>25</option>
          <option>50</option>
          <option>100</option>
          </select>
	</div>
    
    </div>
  </body>
</html>

**Comment by rohansp** [comment]
im unable to copy full html as it renders in browser

**Comment by rohansp** [comment]
Attaching the images of the html..
![html 1](https://cloud.githubusercontent.com/assets/11171608/6347758/6cff39ea-bc40-11e4-8bd0-63952ffaec69.png)

![html 2](https://cloud.githubusercontent.com/assets/11171608/6347786/98a4c7b8-bc40-11e4-887c-b4b2d38a4389.png)

**Comment by rohansp** [comment]
any idea why it doesn't work?whats wrong with the implementation...

**Comment by Zizzamia** [comment]
I assume you should take a look the response of your backend, because your code looks ok.
Is it possible have a `console.log(response.data)`?

Also if you want customize the pagination you should take a look here http://zizzamia.com/ng-tasty/directive/table/custom-pagination

**Comment by rohansp** [comment]
Will have a look at custom pagination.
Attaching image of console.log
![console log](https://cloud.githubusercontent.com/assets/11171608/6389582/361e88c2-bdcb-11e4-848c-aa5026321e30.png)

**Comment by rohansp** [comment]
i figured it out.Created custom pagination html....it works now...

<div tasty-pagination  bind-items-per-page="itemsPerPage" bind-list-items-per-page="listItemsPerPage" template-url="localTemplatePagination.html">
           
 </div>

 <script type="text/ng-template" id="localTemplatePagination.html">
          <div class="row">
            <div class="col-xs-6 text-center" >
              <ul class="pagination">
                <li ng-class="classPageMinRange">
                  <a href ng-click="page.previous()">&laquo;</a>
                </li>
                <li ng-repeat="numPage in rangePage" ng-class="classNumPage(numPage)">
                  <a href ng-click="page.get(numPage)">
                    <span ng-bind="numPage"></span>
                    <span class="sr-only" ng-if="classNumPage(numPage)">(current)</span>
                  </a>
                </li>
                <li ng-class="classPageMaxRange">
                  <a href ng-click="page.remaining()">&raquo;</a>
                </li>
              </ul>
            </div>
            <div class="col-xs-1 text-left">
                <select ng-init="gridpagination.count=10" ng-model="gridpagination.count" ng-change="page.setCount(gridpagination.count)"  >
                <option value="10">10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
                </select>
            </div>
            <div class="col-xs-3 text-right">
                <p>Page <span ng-bind="pagination.page">pagination.page</span> 
                of <span ng-bind="pagination.pages">pagination.pages</span>,
                of <span ng-bind="pagination.size">pagination.size</span> entries</p>
            </div>
          </div>
    </script>

**Comment by rohansp** [comment]
<div tasty-pagination  bind-items-per-page="itemsPerPage" bind-list-items-per-page="listItemsPerPage" template-url="localTemplatePagination.html">
</div>

<script type="text/ng-template" id="localTemplatePagination.html">
          <div class="row">
            <div class="col-xs-6 text-center" >
              <ul class="pagination">
                <li ng-class="classPageMinRange">
                  <a href ng-click="page.previous()">&laquo;</a>
                </li>
                <li ng-repeat="numPage in rangePage" ng-class="classNumPage(numPage)">
                  <a href ng-click="page.get(numPage)">
                    <span ng-bind="numPage"></span>
                    <span class="sr-only" ng-if="classNumPage(numPage)">(current)</span>
                  </a>
                </li>
                <li ng-class="classPageMaxRange">
                  <a href ng-click="page.remaining()">&raquo;</a>
                </li>
              </ul>
            </div>
            <div class="col-xs-1 text-left">
                <select ng-init="gridpagination.count=10" ng-model="gridpagination.count" ng-change="page.setCount(gridpagination.count)"  >
                <option value="10">10</option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="100">100</option>
                </select>
            </div>
            <div class="col-xs-3 text-right">
                <p>Page <span ng-bind="pagination.page">pagination.page</span> 
                of <span ng-bind="pagination.pages">pagination.pages</span>,
                of <span ng-bind="pagination.size">pagination.size</span> entries</p>
            </div>
          </div>
    </script>

**Comment by Zizzamia** [comment]
#Awesome
