### ISSUE TITLE
Page number should be reset after filters change for server resource

### ISSUE THREAD

**Issue by mkaluzny** [Zizzamia/ng-tasty#112]
If you are fetching data from server and filters changed, then current page number should be set to 1, before sending request for filtered data. Currently, if you are on page greater than 1 and after applying filter there is not enough data to display requested page ng-tasty will show empty list for requested page, but it should jump to first page.

**Comment by Zizzamia** [comment]
I think you are in the same case of this issue https://github.com/Zizzamia/ng-tasty/issues/98.
If it's that the case you should update to `v0.5.1`. 

Anyway I'm going to investigate more about it.

**Comment by Zizzamia** [comment]
@mkaluzny can you tell me what version of #ngTasty are you using and also give me an example of your  html and js implementation in this case please. ThankYou

**Comment by Zizzamia** [comment]
@mkaluzny can you give me more info about it, and some code to replicate this issue please.

**Comment by Zizzamia** [comment]
@mkaluzny looks this issue was solve long time ago, if is still not please give me some snip of code we can recreate the issue.
ThankYou
