### ISSUE TITLE
Filter and sorting aren't working

### ISSUE THREAD

**Issue by billfranklin** [Zizzamia/ng-tasty#115]
I am using a service to populate the bind-resource with a JSON data provider.  The data populates fine, and the table paginates, but I am unable to get the filter or the sorting to work.  Here is my table heading and controller 
```html
    <div tasty-table bind-resource="vm.notifications" bind-filters="vm.filters">
        <table class="table table-striped table-condensed">
            <thead bind-not-sort-by="vm.notSortBy">
```
```js
    function HomeController(notificationFactory){
        var vm = this;
        vm.debug = true;
        vm.filters = '';
        vm.notSortBy = [];
        vm.notifications = {'header':[],'rows':[]};

        notificationFactory.list().then(function(data){
            vm.notifications = data;
            return vm.notifications;
        });

    }
```

**Comment by Zizzamia** [comment]
I did not try yet your code, but a possible issue could the fact you don't pass a `$scope` variable.
And the internal `$scope.$watch` can not work properly in this case.

**Comment by billfranklin** [comment]
I added $scope to the controller...didn't change anything.

**Comment by Zizzamia** [comment]
The sorting is not working because you miss add the `tasty-thead` directive.
Here an example of the Complete Tasty table version http://zizzamia.com/ng-tasty/directive/table/complete

**Comment by joamaki** [comment]
I'm having this issue as well. Seems like the simple http example is misbehaving as well: http://zizzamia.com/ng-tasty/directive/table/simple-http. Pressing the headers to sort only works sometimes and only in one direction.

**Comment by Zizzamia** [comment]
Can you please give me an example of code with the Javascript and Markup you are using.
If you guys can recreate the error here will be so easy for me fix it in an hour. ThankYou

**Comment by joamaki** [comment]
As said earlier, the code in the simple-http example shows this. It gets triggered 
when 'watch-resource' is set to 'collection'. Try clicking few times on the "Name" header in the 'simple-http' example and compare it to the behaviour in the 'simple' example.

**Comment by Zizzamia** [comment]
Ops! That looks a bug. I will take care of that, thanks for the feedback.

**Comment by Zizzamia** [comment]
I double check, and in the new version I will release soon `0.5.2` the bug is gone.
