### ISSUE TITLE
No sort on header  key  using underline .  "key": "da3_cod"

### ISSUE THREAD

**Issue by eduavila** [Zizzamia/ng-tasty#124]
Problem sortBy on header using underline ex:  "key":"da3_cod".
Only works the first sort. When you sort the same column does not work.

google translate  :'(

**Comment by Zizzamia** [comment]
This issue it's been fix by @wahidnory few days ago, will be in the next release of #ngTasty in less than a week. https://github.com/Zizzamia/ng-tasty/pull/123
