### ISSUE TITLE
Document and refactoring of loadOnInit

### ISSUE THREAD

**Issue by Zizzamia** [Zizzamia/ng-tasty#131]
After the amazing PR of @flaviogranero it's time to push this feature on production.
The initial PR https://github.com/Zizzamia/ng-tasty/pull/127

And here my commit https://github.com/Zizzamia/ng-tasty/commit/03f4075d850d2364ab97c5eefa5c5f5e0c2d16b2

**Comment by flaviogranero** [comment]
:+1:

**Comment by Zizzamia** [comment]
Tell me if you like it!
http://zizzamia.com/ng-tasty/directive/table-server-side/custom-theme

Btw what is your Twitter account?

**Comment by flaviogranero** [comment]
yes, definitely the bind-theme is more appropriate than having a load-on-init property.
my twitter is @flaviogranero.
