### ISSUE TITLE
tasty-thead, how to change column title in tasty-thead

### ISSUE THREAD

**Issue by tuannnm46** [Zizzamia/ng-tasty#132]
Dear all,

I want to change thead 
[start] scope.resource.header = [{"key": "date","name": "Date"},{"key": "id", "name": "ID"}]

And I have function reloadData(), and change header
[end] scope.resource.header = [{"key": "month","name": "Month"},{"key": "id", "name": "ID"}]

I've used bind-reload="reloadData", scope.resource.header have been changed, but on Table view didn' t changed.

Please help me,  how to change column title in tasty-thead

Thanks,
Minh Tuan

**Comment by Zizzamia** [comment]
Hi @tuannnm46,
I think you just discover a bug!
Here https://github.com/Zizzamia/ng-tasty/blob/master/template/table/head.html#L5 as you can read we use bind-once for all the header data.

So I will take care of this and think a possible solution to disable the bind-once in this case!

**Comment by tuannnm46** [comment]
Hi @Zizzamia,

I'm a newbie.
Thanks you very much.

Thanks,
Minh Tuan.

**Comment by Zizzamia** [comment]
https://twitter.com/Zizzamia/status/610623132831887360
