### ISSUE TITLE
Custom Pagination - user defined template issue

### ISSUE THREAD

**Issue by tonyhayes** [Zizzamia/ng-tasty#134]
I copied the template/table/pagination.html from ng-tsty-tpls.js and placed in an html file (I un-string-ed it, of course).
I then added template-url to the tasty-pagination directive
 				<div tasty-pagination  template-url="crosscap-angular/promo-manager/offers-list/partials/offerslist-pagination-control.html" bind-items-per-page="itemsPerPage" bind-list-items-per-page="listItemsPerPage"></div>

I get an angular error on the $compile statement at line 130 of ng-tasty-tpls.min.js
                   element.replaceWith($compile(templateContent)(scope))

![image](https://cloud.githubusercontent.com/assets/3122115/7716047/db445ae0-fe42-11e4-9117-817b7282e5fc.png)

**Comment by tonyhayes** [comment]
This is caused by leading whitespace in my template. Closing

**Comment by Zizzamia** [comment]
Wow that was a fast closing issue :) 
Have a great day!

**Comment by tonyhayes** [comment]
you may want to consider $trim -ing this before passing into the $compile

also as an fyi - I couldn't get the pagination previous and next page to work.
instead of debugging (sorry) I used page.get in it's place;


![image](https://cloud.githubusercontent.com/assets/3122115/7758351/e5174ed4-ffbd-11e4-9f1c-79cd5aa3ed21.png)
