### ISSUE TITLE
Question : Add a Custom Filter

### ISSUE THREAD

**Issue by CronaFront** [Zizzamia/ng-tasty#136]
Hi, 
I would like to know if it's possible to add a custom filter, my needs is to have a "starts with" filter.
I try to add a filter in the ng-repeat, but of course this break pagination.

Thanks a lot. :)

**Comment by Zizzamia** [comment]
There is not an official way to chain other filter, now it's support only one the "filter".
I will fix this in the new version v0.5.5
ThankYou for the hint.

**Comment by CronaFront** [comment]
Ok, thanks :)

**Comment by Zizzamia** [comment]
The solution of this problem it's here in this docs.
http://zizzamia.com/ng-tasty/directive/table/advance-filters

Please let me know if is enough clear.

**Comment by CronaFront** [comment]
It's really perfect ! Thanks for the job you made on ng-tasty.
Le 12 juil. 2015 07:59, "Leonardo Zizzamia" <notifications@github.com> a
écrit :
