### ISSUE TITLE
Cannot read property 'then' of undefined for the bind-resource-callback

### ISSUE THREAD

**Issue by gofranshukair** [Zizzamia/ng-tasty#137]
Hello,
I am trying to replicate the ng-tasty server-side pagination table.
I am getting this error "Cannot read property 'then' of undefined for the bind"
here :
```js
if (!$scope.reload || $scope.reload && updateFrom !== 'filters') {
      $scope.resourceCallback($scope.url, angular.copy($scope.params))
      .then(function (resource) {
        setDirectivesValues(resource);
      });
```

**Comment by Zizzamia** [comment]
Can you please show me your code that replicate this error.

**Comment by ramzz** [comment]
Hi,

Any progress on this issue?

I'm getting the same error while executing following piece of code with Angular v1.4.1:

view:
bind-resource-callback="admUsrAccListCtrl.getGridData"

controller:
        this.getGridData = function(params, paramsObj) {
            this.resultPrimise = $http.get('http://my_correct_rest_resource');

            this.resultPrimise.then(function(response) {
                    //this.gridSource.rows = response.data;
                    var result = {
                        'rows': response.data,
                        'header': gridHeaders,
                        'pagination': true,
                        "sortBy": "id",
                        "sortOrder": "desc"
                    };
                    console.log(result);
                    return result;
                });
        };


After this I'm getting correct output to the console, but grid is not being populated and following error is displayed:

TypeError: Cannot read property 'then' of undefined
    at updateServerSideResource (ng-tasty-tpls.js:385)
    at Scope.$get.Scope.$eval (angular.js:15830)
    at Scope.$get.Scope.$digest (angular.js:15641)
    at Scope.$get.Scope.$apply (angular.js:15935)
    at done (angular.js:10356)
    at completeRequest (angular.js:10528)
    at XMLHttpRequest.requestLoaded (angular.js:10469)

**Comment by Zizzamia** [comment]
Hi @ramzz, as you can read in the documentation you forget to return your `$http` promise.
http://zizzamia.com/ng-tasty/directive/table-server-side/complete

```js
        this.getGridData = function(params, paramsObj) {
           var urlApi = 'http://my_correct_rest_resource';
            return $http.get(urlApi).then(function(response) {
                    var result = {
                        'rows': response.data,
                        'header': gridHeaders,
                        'pagination': true,
                        "sortBy": "id",
                        "sortOrder": "desc"
                    };
                    console.log(result);
                    return result;
                });
        };
```
Please let me know if will work.

**Comment by Zizzamia** [comment]
Hey @gofranshukair,
probably the reason is not working it's because you should add a `return` on your callback.
Can you please let me know if was that the problem, and maybe show me your implementation.

**Comment by Zizzamia** [comment]
After almost a month of this issue is open and looks there are not more info about, I will close it. Let me know guys if the problem still exist.
