### ISSUE TITLE
Client side pagination and itemsPerPage

### ISSUE THREAD

**Issue by seminull** [Zizzamia/ng-tasty#138]
I was curious as to why in setRemainingRange and setPreviousRange functions that itemsPerPage were even used at all when it comes to incrementing and decrementing whole 'pages'?  This caused the page.remaning() and page.previous() buttons to not work as expected.

**Comment by Zizzamia** [comment]
Can you please show me some code where this error happen.

**Comment by seminull** [comment]
It took some time to reproduce it from scratch but I found the culprit or at least better information.

```html
<div tasty-pagination items-per-page="25"></div>
```

http://www.seminull.com/angular/ngtasty/#/

**Comment by ddavison732** [comment]
This problem is not only client side, but also a problem for server side pagination. Basically the code below leads to the page buttons acting like you are at the end of the list of page numbers before you actually are. You can see it [on the project's example site](http://zizzamia.com/ng-tasty/directive/table-server-side/pagination). You can't get 7 to show in the pagination when clicking the next pages arrows.

```
setRemainingRange = function () {
  if (scope.pagHideMaxRange === true || scope.pagMaxRange > scope.pagination.pages) {
    return false;
  }
  scope.pagMinRange = scope.pagMaxRange;
  scope.pagMaxRange = scope.pagMinRange + scope.itemsPerPage;
  if (scope.pagMaxRange > scope.pagination.pages) {
    scope.pagMaxRange = scope.pagination.pages;
  }
  scope.pagMinRange = scope.pagMaxRange - scope.itemsPerPage;
  setPaginationRanges();
};
```

**Comment by seminull** [comment]
@ddavison732 that's slightly different than the problem I'm describing here, but I know what you are referring to.  I have a PR out for it, as soon as I can figure out unit tests in JS. :)

**Comment by ddavison732** [comment]
Ok, sorry for the confusion.

**Comment by Zizzamia** [comment]
The range pagination is not working in a couple of case. I try to use your PR @seminull but is not enough to cover all the two case where there is the errors, and also is not passing the old tests.
I'm going tomorrow try to come out with a more stable fix.
ThankYou both to help me focus on this problem. :)

**Comment by Zizzamia** [comment]
So, was not so simple find the time to do this fix, 
but in the end by your helps I made the commit that fix this bug. 
ThankYou for the help and all the information you share with me.

**Comment by seminull** [comment]
Thanks @Zizzamia you're awesome!

**Comment by ddavison732** [comment]
I haven't downloaded the changes yet but thanks for maintaining this awesome project.

**Comment by Zizzamia** [comment]
The change will be up on the next release. I'm sorry for the delay but it's been few busy weeks in Twitter.

**Comment by Zizzamia** [comment]
https://twitter.com/Zizzamia/status/610623132831887360
