### ISSUE TITLE
Server Side search pagination

### ISSUE THREAD

**Issue by cubasepp** [Zizzamia/ng-tasty#142]
Hi,

for example. 
If you stay on page 5 and search for something and the result has only 2 pages you get an empty response from the server. Because the ngTasty doesn't reset the page attribute after  the filter function was called. ( // AngularJs $watch callbacks if ($attrs.bindFilters) {  .. })

Maybe you have to reset the page attribute so you get a result. 

http://zizzamia.com/ng-tasty/directive/table-server-side/complete you can see it on your demo.

go on page 4 and search for something on page 1 but your page attribute stays on 4 so you see no result.

**Comment by ranjithdharmaraj** [comment]
Yes, I have the same issue..I see from the past issues that this was reported earlier but closed as fixed.
Ex: http://zizzamia.com/ng-tasty/directive/table-server-side/complete. Go to page 3 and then enter "wicked" in Filter by name text field. 
It does not bring up the one record that exists

**Comment by luigima** [comment]
Don' t know why https://github.com/Zizzamia/ng-tasty/issues/98 should be fixed, I have the same issue with version "0.5.4 - 2015-05-04".

Maybe we should add a "bind-pagination" attribute to the ngTasty directive? We could reset the page manually then.

**Comment by Zizzamia** [comment]
Please update ng-tasty to the version 0.5.5 and let me know if the error it still present. ThankYou

**Comment by luigima** [comment]
No, same issue with 0.5.5..

**Comment by Zizzamia** [comment]
Ou ok! I will fix this for the version 0.5.6

**Comment by cubasepp** [comment]
You have to reset the page attribute at the URL. 
"table.json?sort-by=name&sort-order=dsc&page=3&count=5&name=Wick"

The result have only 1 page but we display Page 3... ;) 

Thx Zizzamia

**Comment by Zizzamia** [comment]
Just release the version  0.5.6

**Comment by thesilverbadger** [comment]
0.5.6 has fixed the issue with the page not resetting on a new search, however the pagination buttons (5, 25, 50, 100 and 1-5 etc) no longer page through the resultset or change the number of returned results when clicked. They only take effect when the search is subsequently manually performed.

Do you want me to raise a new issue for this?

**Comment by Zizzamia** [comment]
@thesilverbadger yes please, looks a serious to fix a soon as possible.
Can you open a new issue by showing the code that you are using and tell me the action you doing.
Will make my work faster.
#ThankYou
