### ISSUE TITLE
remaining pages button in pagination

### ISSUE THREAD

**Issue by berc** [Zizzamia/ng-tasty#143]
When I click on remaining-pages-button in your simple table example pagination, it shows me only last page 6 and I am remaining-pages-button button is disabled. But there are 7 pages.

Do you have some explanation for this, or is it a bug?

**Comment by seminull** [comment]
@berc this will be fixed once #138 is released

**Comment by Zizzamia** [comment]
Thanks @seminull, sorry for the delay for the new feature. Make sure to have this release on the weekend. I'm changing team on Twitter and I didn't have so much time to work on open source stuff :(
See you soon! Grazie
