### ISSUE TITLE
ng-hide and ng-if

### ISSUE THREAD

**Issue by ckreddy08** [Zizzamia/ng-tasty#144]
Hi, how do I hide some columns and show them on click. I tried using "th ng-show="true" tags instead of "tasty thead" but the sort is not working if I do that. Any work around? 

Thanks in advance

**Comment by Zizzamia** [comment]
A work around could be you make your own custom `thead` for now.

```html
<div tasty-table bind-resource="resource" bind-theme="customTheme">
  ...
</div>
```

```js
$scope.customTheme = {
  templateHeadUrl: 'template/table/my-custom-head.html'
};
```
And pretty much you are going to make your custom thead, by coping the existing one and add your custom feature.

Is it clear?
I'm going to use this task to make an example in the docs.

**Comment by Zizzamia** [comment]
There was not update of this issue for few months, I'm going to close it! Thanks
