### ISSUE TITLE
ng-tasty has wrong entry point in package.json

### ISSUE THREAD

**Issue by clintonhalpin** [Zizzamia/ng-tasty#145]
If I run ```npm install ng-tasty``` and try to require it with browserify / webpack

```
require('ng-tasty')
```

I get an error because the main property in ```package.json``` points to ```index.js``` which doesn't exist. This fixes it.

```
// package.json

{
  ...
  "main": "ng-tasty-tpls.js",
  ...
}
```

**Comment by Zizzamia** [comment]
ThankYou @clintonhalpin, I will fix this issue in the next 0.5.7 version of npm.
