### ISSUE TITLE
0.5.6 - Paging buttons have stopped working

### ISSUE THREAD

**Issue by thesilverbadger** [Zizzamia/ng-tasty#148]
0.5.6 has fixed our issue with the page param not being reset to 1 on a search being triggered, however this seems to have introduced a new bug whereby the pagination buttons no longer page through a remote resultset.

I think I've tracked the issue down to `updateServerSideResource`, which fires when the pagination buttons are clicked, but as `initNow` is always false (we don't want the search triggering when the page is initalised), resourceCallback is never called.  Our search button is hooked up to a callback, and this triggers correctly (and seems to take the correct params too, so if I've clicked page 5, and then click search, I get results from page 5).

```js
$scope.reloadCallback = function () { };
$scope.search = function () {
  $scope.reloadCallback();
};
```

I'm of work now for a week (:tropical_drink: :sunny:), so I'll try to provide a demo when I return if this isn't enough info.

Cheers :smile:

**Comment by thesilverbadger** [comment]
Looks fixed to me, many thanks :)

**Comment by Zizzamia** [comment]
:) thankYou
