### ISSUE TITLE
paramsObj does not match params

### ISSUE THREAD

**Issue by InsidersByte** [Zizzamia/ng-tasty#153]
# paramsObj does not match params

I am using angular resources and it is easier to pass the params object into the get method than build my own search string up. However I noticed that the paramsObj and params do not match. I have attached a screenshot taken today from the demo website.

![paramsobjnotmatchingparams](https://cloud.githubusercontent.com/assets/6938575/8852008/af8bff26-314a-11e5-9d64-4069e2fcbdda.png)

**Comment by Zizzamia** [comment]
What value are not matching? And what page are you watching exactly? Thanks

**Comment by InsidersByte** [comment]
I was looking at http://zizzamia.com/ng-tasty/directive/table-server-side/complete.

I was expecting that when you enter a value for the filter by name and/or a filter by location that these values would appear in the paramsObj.

For example I set filter by name to 'a' and filter by location to 'b'.

The resulting params was
```
sort-by=name&sort-order=dsc&page=1&count=5&name=a&sf-location=b
```

and the resulting paramsObj was
```
{"thead":true,"pagination":true,"count":5,"sortBy":"name","sortOrder":"dsc","page":1}
```

I was hoping that paramsObj would look like this
```
{"thead":true,"pagination":true,"count":5,"sortBy":"name","sortOrder":"dsc","page":1,"name":"a","sflocation":"b"}
```

**Comment by Zizzamia** [comment]
ThankYou @InsidersByte to reporting this important bug, I'm releasing right now a new version of #ngTasty with this fix. Please let me know if there are other issue with #ngTasty :-)

**Comment by InsidersByte** [comment]
Thank you for fixing this so quickly :+1:
