### ISSUE TITLE
pagination can't show the max page

### ISSUE THREAD

**Issue by baijiezi** [Zizzamia/ng-tasty#154]
Hello:
I return the pagination form the js file like this:
```js
'pagination': {
              "count": 100,
              "page": 1,
              "pages": 22,
              "size": 2158
            }
```
When I click the remaining button to change pages, it can show page 16, but can't show the page 22.

on the right of the page，it show this info:
Page 1 of 22, of 2158 entries

**Comment by Zizzamia** [comment]
I had problem to recreate the bug, can you please show me your implementation.

**Comment by baijiezi** [comment]
angular.module('healthApp')
  .controller('HospitalReport2Ctrl', ['$rootScope', '$scope', '$state', '$http','$filter',
    function ($rootScope, $scope, $state, $http, $filter, $cookieStore) {
      $scope.startDate = new Date(new Date()-1000*60*60*24*2);
      $scope.endDate = new Date(new Date()-1000*60*60*24);
      $scope.templateUrl = 'views/templates/p.html';
      $scope.count = 100;
      $scope.page = 1;

      $scope.init = {
        'count': $scope.count,
        'page': $scope.page
      };
      $scope.filterBy = {
        'startDate': $filter('date')($scope.startDate, 'yyyy-MM-dd'),
        'endDate': $filter('date')($scope.endDate, 'yyyy-MM-dd')
      };
      $scope.getResource = function (params, paramsObj) {
        params = params.replace(new RegExp('count', 'g'), 'per_page');
        var urlApi = restUrl + '/statements/hospitalTransRecord?' + params;
        return $http.get(urlApi).then(function (response) {
          return {
            'rows': response.data.data.pageList,
            'header': [
              {
                "key": "hospitalName",
                "name": "Hospital"
              },
              {
                "key": "merchantId",
                "name": "MerchanId"
              },
              {
                "key": "payCardNo",
                "name": "PayCard"
              }
            ],
            'pagination': {
              "count": response.data.data.pageSize,   //100
              "page": response.data.data.curPage,     //1
              "pages": response.data.data.totalPage,  //9
              "size": response.data.data.totalCount   //852
            }
          }
        });
      }
  }])

**Comment by baijiezi** [comment]
<div class="row">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                <div class="caption">HospitalReport2</div>
            </div>
            <div class="panel-body">
                <div tasty-table bind-resource-callback="getResource" bind-init="init" bind-filters="filterBy">
                    <table class="table table-striped table-condensed">
                        <thead tasty-thead></thead>
                        <tbody>
                        <tr ng-repeat="row in rows">
                            <td>{{ row.hospitalName }}</td>
                            <td>{{ row.merchantId }}</td>
                            <td>{{ row.payCardNo }}</td>
                        </tr>
                        </tbody>
                    </table>
                    <div tasty-pagination bind-list-items-per-page="[5, 25, 55, 100]" bind-template-url="templateUrl"></div>
                </div>

            </div>
        </div>
    </div>
</div>

**Comment by baijiezi** [comment]
![page1](https://cloud.githubusercontent.com/assets/4739010/8897879/13b777d0-344f-11e5-8650-3244f34c363c.png)


![page2](https://cloud.githubusercontent.com/assets/4739010/8897904/869a59f2-344f-11e5-8edd-057f5db543be.png)

**Comment by baijiezi** [comment]
The problem has been resolved
by update ng-tasty to v0.5.7.
Thank you.

**Comment by Zizzamia** [comment]
Yeee :-) :+1: 
ThankYou
