### ISSUE TITLE
Reload serverside rows after deleting a row

### ISSUE THREAD

**Issue by vidvid** [Zizzamia/ng-tasty#155]
I have a 'delete' icon in each row of my server-side table. I delete the row from database using a http call. Afterwards I need to reload the table. I didn't happen to find any solution for this in the documentation. It seems that bind-reload function is only applicable when working with filters.

**Comment by patrickchampclos** [comment]
Hi. You can bind your http callback by calling a function that will reload the table manually using bind-reload directive.

**Comment by vidvid** [comment]
Thanks @patrickchampclos but I've done this and it doesn't work. It's because of the fact that reload function seems to be effective only when filter values have been changed. Am I doing something wrong?

**Comment by vidvid** [comment]
@Zizzamia I think this is related to #114 
I suggest we close that one as you mentioned and mark this as a bug.
We've been waiting for this issue a long time and I hope we can have this done soon.

**Comment by Zizzamia** [comment]
I'm still sure it's a not a real bug.
I'm here http://zizzamia.com/ng-tasty/directive/table-server-side/reload and anytime I click search
will be fired a xhr request to the server.

Also in local I tried to give different backend response any time I click search, and the table it's been modified correctly.

Do you have some code I can use to replicate this bug?
Thanks!

**Comment by vidvid** [comment]
Here is my controller code (coffeescrpit):

    constructor: ($scope, $rootScope, $log, $filter, NotificationsAdminService, $state, $modal, tableConfig) ->
    $log.debug("creating NotificationsAdminCtrl")
    tableConfig.loadOnInit = true
    $scope.loadingData = true;
    $scope.totalNotificationsCount = 0;

    $scope.initTable =
      'count': $scope.rowCount
      'page': 1
      'sortBy': 'date'
      'sortOrder': 'dsc'
    $scope.reloadCallback = () ->

    $scope.filters =
      var1: ''
      var2:''

    $scope.search = () ->
      $log.info "search clicked"
      $scope.reloadCallback()

    $scope.loadNotifications = (params, paramsObj) ->
      $scope.loadingData = true
      $scope.changeRowCount paramsObj.count

      result = NotificationsAdminService.getNotifications(params)
      ret = result.then((response) ->
        $scope.notifications = response.data.page
        $scope.totalNotificationsCount = angular.copy(response.data.total)
        table = {
          'rows': $scope.notifications
          'header': [
            {
              key: 'date'
              name: 'Date'
              style: {'width': '15%'}
            }
            {
              key: 'type'
              name: 'Type'
              style: {'width': '30%'}
            }
            {
              key: 'recips'
              name: 'Recipients'
              style: {'width': '25%'}
            }
            {
              key: 'importance'
              name: 'Importance'
              style: {'width': '15%'}
            }
            {
              key: 'info'
              name: ''
              style: {'width': '15%'}
            }
          ]
          'pagination': {
            "count": paramsObj.count
            "page": paramsObj.page
            "pages": Math.ceil(response.data.total / paramsObj.count)
            "size": response.data.total
          },
          'sortBy': 'date'
          'sortOrder': 'dsc'
        }

        $scope.loadingData = false
        return table
      )
      return ret


And this is my html code:

    <div tasty-table bind-resource-callback="loadNotifications" bind-init="initTable" bind-filters="filters" bind-reload="reloadCallback" >
                <div class="row form-inline">
                    <div class="col-sm-12">
                        <div class="pull-right">
                            <div class="dataTables_filter">
                                <label>
                                    <input id="searchInput" type="text" ng-model="filters.search" data-ng-model-options="{debounce: 1000}"
                                           nxe-autofocus="1000" class="form-control" placeholder="Search">
                                </label>
                                <button ng-click="search()">reload</button>
                            </div>
                        </div>
                       
                    </div>
                </div>

                <table id="notificationTable" class="table no-border" ng-show="!loadingData">
                    <thead tasty-thead template-url="/assets/partials/table/header.html" not-sort-by="['info','recips']"
                           icon-up="sorting_asc" icon-down="sorting_desc" class="no-border"></thead>
                    <tbody>
                    <tr data-ng-repeat="notification in rows" ng-class-odd="'odd'" ng-class-even="'even'"
                        class="gradeC">
                        <td class=" "><a
                                ui-sref="admin.notifications.view.subMenu({id:notification.id,menu:'overview'})">{{notification.date}}</a></td>
                        <td class="hidden-xs ">
                            <span class="label label-default">{{notification.type | capitalize}}</span>
                        </td>
                        <td class="hidden-xs ">
                                    <span class="label label-default" style="margin-right: 3px;"
                                          data-ng-repeat="recip in notification.recipients"
                                          data-ng-show="recip.recipientCategory!=null">
                                        {{recip.recipientCategory}}
                                    </span>

                                    <span class="label label-default"
                                          data-ng-repeat="recip in notification.recipients"
                                          data-ng-show="recip.cid!=null">
                                        {{recip.cid}}
                                    </span>
                                    <span class="label label-default"
                                          data-ng-repeat="recip in notification.recipients"
                                          data-ng-show="notification.recipients.length>3">
                                        <i style="top:2px; position: relative;" class="fa fa-ellipsis-h"></i>
                                    </span>
                        </td>
                        <td class="hidden-xs ">
                            <span class="label label-default">{{notification.importance | capitalize}}</span>
                        </td>
                        <td class="right ">
                            <a ng-click="onUserSelected(user, $index)"
                               ui-sref="admin.notifications.view.subMenu({id:notification.id,menu:'overview'})"
                               class="label label-primary tooltip-top" nxe-tooltipster="Overview">
                                <i class="fa fa-fw fa-info"></i></a>
                            <a href="" class="label label-primary hidden-xs tooltip-top" nxe-tooltipster="Delete" id="notificationDelete"
                               data-ng-click="deleteNotification(notification.id, $index)">
                                <i class="fa fa-fw fa-times"></i>
                            </a>

                        </td>
                    </tr>
                    </tbody>
                </table>


When I click *reload* button, the search method is called and my own *reload* function is called but table is not reloaded. 

maybe this helps: 
should calling the reloadCallback function execute the one that I define in controller or is it overriden by ngTasty? Because If I put a log in the reloadCallback, I actually see it in the console.

**Comment by Zizzamia** [comment]
Your `reloadCallback` should be called after you invoke the reload function.
What response you get in `ret = result.then((response) ->` after you invoke the reload function?

And you still say that is broke after you delete a row, right? only in that case is not working?!

**Comment by vidvid** [comment]
@Zizzamia  what do you mean by invoking the reload function. If you mean the method declared as bind-resource-callback (in my case loadNotifications) I don't call it manually. And If you mean the 'search' method, yes I call it when I click the button but nothing happens. my reloadCallback is called and then nothing.

**Comment by Zizzamia** [comment]
Here a demo of what you are looking for http://zizzamia.com/ng-tasty/directive/table-server-side/reload
Please let me know if there still bug about this topic.

This demo use `ngTasty v0.6.0`

**Comment by vidvid** [comment]
Thanks a million @Zizzamia  for your example.
After a long period of comparing and debugging, I found that the problem was due to the fact that my state didn't have any controller and used a parent controller and that made the problem of reload callback not being effective. I don't now why this prevents reload but after that change everything worked like a charm. 
Thanks I guess we can close this one.

**Comment by Zizzamia** [comment]
:-)

**Comment by darkmakukudo** [comment]
@Zizzamia I can still replicate the issue using ngTasty v0.6.1
