### ISSUE TITLE
Filter delay?

### ISSUE THREAD

**Issue by duongtdvn** [Zizzamia/ng-tasty#157]
I have used ng-tasty for a while and it quite smooth, and I have suggest on the filter directive. It should have some delay before firing action, currently when i type something in the input filter it trigger every word, and it may cause the result not filtered, displayed correctly especially filtering with server side. For example in your demo site:

![Image of example]
(http://i.imgur.com/kr0RKSV.png)

**Comment by Zizzamia** [comment]
I think it's already possible doing with the current #ngTasty, but I will give a look and make a doc to explaing how do it.

Thanks to open this issue.

**Comment by duongtdvn** [comment]
Hi,
Can you please refer me to any params or bind- to use the delay?

Thank you for quick response!

**Comment by vidvid** [comment]
@duongtdvn have you tried using ng-model-options on your filter input component?
I'm using this feature now and I have no problem with it. Here is the code I'm using:
`<input type="text" ng-model="filters.search" ng-model-options="{debounce: 1000}">`

**Comment by duongtdvn** [comment]
@vidvid yea, I have tried with that option but seem to not working, the filter action is not firing anymore, actually nothing happen when i type in the input field.

**Comment by vidvid** [comment]
@duongtdvn can you provide a jsFiddle? As I said I am using this and it's working perfectly. One issue I have seen is that sometimes when I give the filters object a name other than 'filters' it doesn't work. It might be my mistake but you can try this too.

**Comment by duongtdvn** [comment]
Ah okay, never mind, I made it work, just removed the $scope.filters by accident, things got solved now!

Thank you guys!

**Comment by Zizzamia** [comment]
Nice! Thanks @vidvid for the help.
