### ISSUE TITLE
ParamsObj causing circular object JSON error

### ISSUE THREAD

**Issue by ddavison732** [Zizzamia/ng-tasty#159]
No problems with 0.5.5, but if I jump to 0.5.8, I get this error
`TypeError: Converting circular structure to JSON`

It seems paramsObj is now giving an object with a circular structure where it was not before. It is including my filters object in it automatically now, breaking things.

**Comment by ddavison732** [comment]
I could change a whole bunch of code in order to support the change but please update changelog to reflect this breaking change.

**Comment by Zizzamia** [comment]
ThankYou for the hands up, the `paramsObj ` missed `filters object` and was causing problem for the server-side version. 
Do you want update the CHANGELOG please?

**Comment by ddavison732** [comment]
Opened pull request for CHANGELOG update. [Pull Request](https://github.com/Zizzamia/ng-tasty/pull/164)

**Comment by Zizzamia** [comment]
That's awesome! ThankYou so much

**Comment by Zizzamia** [comment]
Also just release on bower the version `0.5.9` with this fix in it!
