### ISSUE TITLE
Reload table on specific page

### ISSUE THREAD

**Issue by brunoaduarte** [Zizzamia/ng-tasty#160]
Hello, i'm using the server side table: 

```html
<div tasty-table bind-resource-callback="getResource" bind-init="init" bind-filters="filterBy"> ...
</div>
```

How do i reload the table to a specific page after removing some item at that page (eg. page 5) ?
Here's how i reload the table: 

```js
$scope.filterBy.changeDetector = !$scope.filterBy.changeDetector;
```

but it always goes to page 1.

i've tried setting $scope.init.page to the last page number before changing the `filterBy.changeDetector`, but nothing happened.

Thanks !

**Comment by thiagofmam** [comment]
I got the same bug. Do you have any fix?

**Comment by Zizzamia** [comment]
So, usually the page return to 1 when a filter is applied to the table, because by filtering something you will probably have less or more stuff to show. As default will always go back to 1.

What you instead guys want, is keeping the same page or the last possible available if the you filter the table in some way.

Am I understood correctly? Because if is like that, we need make some sort of API feature to turn on and off this special case.

**Comment by thiagofmam** [comment]
I'd like use the last params used at the getResource and stay on the page what register was edited. Sorry my english.

**Comment by thiagofmam** [comment]
Could I change the params used at getResource or reload the table without change the filterBy?

**Comment by thiagofmam** [comment]
I created two property and update the method. Now it work. I need add to filterBy the params: page and reloadTable;

Code:

 updateServerSideResource = function (updateFrom, newValue, oldValue) {
      if (updateFrom === 'filters') {
          var resetPage = false;
          var hasBreak = false;
          var hasNewproperty = true;
          if (newValue.page) {
              for (var oldproperty in oldValue) {
                  if (oldproperty === 'reloadTable' || oldproperty === "page") {
                      continue;
                  }
                  for (var newproperty in newValue) {
                      if (newproperty === 'reloadTable' || newproperty === "page") {
                          continue;
                      }
                      if (oldproperty === newproperty) {
                          hasNewproperty = false;
                          if (oldValue[oldproperty] !== newValue[newproperty]) {
                              resetPage = true;
                              hasBreak = true;
                          }
                          break;
                      }

                  }
                  if (hasNewproperty) {
                      resetPage = true;
                      break;
                  }
                  hasNewproperty = true;
                  if (hasBreak) {
                      break;
                  }
              }
          } else {
              resetPage = true;
          }
          if (resetPage) {
              $scope.params['page'] = 1;
          } else {
              $scope.params['page'] = $scope.params.page;
          }
         
      }
    $scope.url = buildUrl($scope.params, $scope.filters);
    if ($scope.reload) {
      $scope.reload = function () {
        $scope.resourceCallback($scope.url, angular.copy($scope.params))
        .then(function (resource) {
          setDirectivesValues(resource);
        });
      };
    }
    if (initNow || updateFrom === 'params') {
      var paramsObj = angular.copy($scope.params);
      paramsObj.filters = $scope.filters;
      $scope.resourceCallback($scope.url, paramsObj)
      .then(function (resource) {
        setDirectivesValues(resource);
      });
    }
  };

Thank you.

**Comment by vidvid** [comment]
> What you instead guys want, is keeping the same page or the last possible available if the you filter the table in some way.

@Zizzamia Yes that's exactly what I need. As another example suppose that there is a refresh button on top of table which reloads the table using the same parameters.

**Comment by yywmrz** [comment]
Where i can find the version 0.5.9 ?I just encounter the same problem

**Comment by yywmrz** [comment]
i am a new guy who use github . i can't understand the content verywell cause English is not my mother language . Sorry

**Comment by Zizzamia** [comment]
I create a new option name `filterBase` inside the init object, for use it you just need do this 
```js
$scope.init = {
    'count': 5,
    'page': 1,
    'sortBy': 'name',
    'sortOrder': 'dsc',
    'filterBase': 1
  };
```

if you set `filterBase` to `false` you will disable the auto reset to a specific page, and will be showed the old one or the last possible useful one.

Happy Holidays, and many thanks to push it hard on this. 😄
✨✨✨

**Comment by smargovsky** [comment]
:+1:

**Comment by Zizzamia** [comment]
Also just release on bower the version `0.5.9` with this fix in it!

**Comment by thiagofmam** [comment]
Thank you so much!

Happy Holidays!
