### ISSUE TITLE
Trigger search api trigger only when the query has more than N characters

### ISSUE THREAD

**Issue by sandeepan** [Zizzamia/ng-tasty#162]
Just wanted to know if there's any in built option for this. I am thinking of quick workaround in getResource function to check for query length.

**Comment by Zizzamia** [comment]
No really, sorry! But please share your version, I could use it to improve the documentation as possible custom solution.

**Comment by sandeepan** [comment]
I needed to finish it quickly. So just did the following

```javascript
var params = params.split("&");
for (param i=0;i<params.length;i++) {
    var pair = param[i].split("=");
    if pair[1] < MINIMUM_REQUIRED_LENGTH {
     doSomething(parmas);
    }
    else {
      doSomethingElse(params)
    }
  } 
```
Just started with angular and js both. So don't really know how to write a directive or make changes to ng-tasty code.
