### ISSUE TITLE
How can I cause the table to refresh programatically?

### ISSUE THREAD

**Issue by firecentaur** [Zizzamia/ng-tasty#163]
Hi there,

My bind-resource-callback is set to a function makes a request to my server to retrieve the table data.
Before I send the request though, I also send the values of 3 check boxes in my user interface.

I am now trying to trigger a table refresh when these checkboxes are checked/unchecked in my user interface.

I am stuck however, because I see that the bind-resource-callback function needs to have to parameters: (params, paramsObj) and I don't know how to access these values since they are bound within your directive (numPages and count)

Can you tell me how I can 1) either retrieve these params, so I can manually call my callback when a checkbox is checked, or 2) tell me how to trigger a refresh of the table data?

Thanks

**Comment by firecentaur** [comment]
Ah!  I figured it out!  using the bind-reload!

**Comment by Zizzamia** [comment]
Awesome!
