### ISSUE TITLE
multipe tables - dynamic tables

### ISSUE THREAD

**Issue by sali1982** [Zizzamia/ng-tasty#174]
Hi,

I am going to try and make dynamic tables. I wonder if it is possible at all?

What I need to do is based on what user clicks, I want to open a new table in a accordion panel.
Each table must have its own data and its own sources , and its own pagination.

Do you know how the pagination will understand it is for which table on the same controller?

Thanks for your response.

**Comment by Zizzamia** [comment]
Any table is independent to each other, I will say... start writing some code and I will help you complete if you have some issue.

**Comment by sali1982** [comment]
Thanks. 

Okay, I am doing it like a dynamic table. When we click on a link, it will get new data and creates a table in a separate Accordion:
<uib-accordion close-others="onAtATime">
            <uib-accordion-group ng-repeat="group in groups" >
               <uib-accordion-heading>
                 {{group.title}}            
               </uib-accordion-heading>
            {{group.content}}
            <div tasty-table bind-resource-callback="getFiles" bind-list-items-per-page="group.pageFilters" bind-init="group.init" bind-theme="group.myTheme" bind-filters="group.filterBy" bind-reload="reloadCallback">
              <table class="tastyTable">
                <thead tasty-thead  >
                </thead>
                <tbody>
                  <tr ng-repeat="row in group.files"  >
                    <td>{{ row.fileName }}</td>
                    <td>{{ row.fileSize }}</td> 
                  </tr>
                </tbody>
              </table>
              <div tasty-pagination bind-template-url="paginationTemplate"></div>
            </div>
            </uib-accordion-group>
          </uib-accordion>

I could have an object called groups, and push to it when a new table needed to be created.
My issue is the functions:  bind-resource-callback="getFiles"

I need to pass the group to that function to call this function with the group is clicked on. But it is not possible. Another way was, to have my function in the object. So every time I push all the attributes and the function call... and change this line to:  bind-resource-callback="group.getFiles"

That is not possible maybe.

What is your suggestion? The tables are purely dynamic.

Thanks,

**Comment by sali1982** [comment]
This is strange that I cannot post html here. I did put an space for html tags. there must be an easy way!

**Comment by Zizzamia** [comment]
I think the best thing is you create a Plunker, so I can code there and help you for your problem.
http://plnkr.co/edit/DNJVQXT7NnNk5k1flqQ2?p=preview

**Comment by sali1982** [comment]
I did fix it. Thanks. It was easy to do. group.getFiles was working as the function in the array of objects.

**Comment by Zizzamia** [comment]
Nice!
