### ISSUE TITLE
Table function runs twice when it is in an Angular-Material mdTab directive

### ISSUE THREAD

**Issue by kevinlbatchelor** [Zizzamia/ng-tasty#176]
I'm using angular-material, and ngTasty and I cannot figure out why the tasty table is running twice when it is added inside one of the angulars md-tab directive. Something either in material or tasty. Of course my table function is making a rest call which is now firing twice.

http://jsfiddle.net/s46gs95e/

**Comment by Zizzamia** [comment]
For a reason I don't understand yet, when `ngTable` was contained inside the Material Tab, the 'params' was detected change after the initialization, and was again calling the `xhr`.
I fixed by making sure that `ngTable` will run max one `xhr` at a time.

**Comment by Zizzamia** [comment]
Also just release on bower the version `0.5.9` with this fix in it!
