### ISSUE TITLE
bug with headers

### ISSUE THREAD

**Issue by epetitje** [Zizzamia/ng-tasty#179]
Hello,

I'm using ng-Tasty to dynamically display data on a page (using bind-resource-callback and bind-reload).
everything works fine until I try in my bind-resource callback to return a table different than the one already displayed (different number of colons).

The data is displayed correctly but the headers are not refreshed properly...
is there a way to reinitialize a tasty-table so everything works fine or is it a bug ?

Thanx,

Etienne

**Comment by Zizzamia** [comment]
I see, you try to use the same `HTML` but with different data.
Can you paste me some code to recreate the bug please.

**Comment by Zizzamia** [comment]
Sorry was not a bug, but just a native feature of ngTasty.
As default all the header it's build by using `bind-once`, to disable that you can check on this page
http://zizzamia.com/ng-tasty/directive/table-server-side/complete `bind-theme` and how switch `bindOnce: true` to `bindOnce: false`.
