### ISSUE TITLE
Reload  rows after deleting a row

### ISSUE THREAD

**Issue by amirafroozeh1** [Zizzamia/ng-tasty#180]
Can you provide a sample example that shows a table with delete button for each row. Then, you can delete a row and have an updated table with true pagination.

**Comment by Zizzamia** [comment]
Here the documentation about delete row and manually reload the table 
http://zizzamia.com/ng-tasty/directive/table-server-side/reload

**Comment by ShayalJindal** [comment]
Hello .. Please help me .. I am facing an issue with ng-Tasty..
The table is not reloading after deleting an entry if I don't use reloadCallBack approach. And if I use reloadCallBack approach, pagination after filter doesn't work. I want reload table after delete with pagination working after filtering too.
