### ISSUE TITLE
List refresh

### ISSUE THREAD

**Issue by aparolini** [Zizzamia/ng-tasty#186]
Hello,

I have a changing list on the server.

I want my table to auto-load the list when the pages loads, thus I used _bind-resource-callback_. Then I want to be able to refresh my list by hand, thus I used _bind-reload_. 

First bug: When I use _bind-reload_, the list is empty when the table appears the fist time. I have to click the button to invoke the reloadCallback. I want the list to be loaded without action the fist time!

Second bug: When using _bind-reload_ and a filter, the _paramsObj_ dosen't content the "filters" attribute.

Thanks in advance for your help

-antonio

**Comment by Zizzamia** [comment]
Ciao @aparolini,
the `bind-reload` functionality give to you the power to load the table when you want.
Here the official docs http://zizzamia.com/ng-tasty/directive/table-server-side/reload
as you can see you create a `$scope.reloadCallback = function () {};`
and you can just call that function when you load your page.
I hope can help!

About the second question, looks like a real bug, and I'm going to take care of that now!
Thanks

**Comment by Zizzamia** [comment]
Also I discover an other bug, to recreate we need change the page and after try to filter the table.
Will happened that the manul `bind-reload` will not work properly.

**Comment by Zizzamia** [comment]
Your fix it's in the latest release https://github.com/Zizzamia/ng-tasty/releases/tag/v0.6.0

**Comment by codenamerana** [comment]
Can you please tell exactly how to solve Bug1 of @aparolini .

I wrote this to initialize the table of page load.

`<div ng-init='reloadCallBack()'></div>`

But sadly this is not working :(

**Comment by Zizzamia** [comment]
Bug1 was not a bug at all, it's just the way the table works, `bind-reload` gives to you the power to load when you want. 

Did you try to do 
```js
$timeout(function () {
  reloadCallback();
});
````

It's possible you need wait a digest loop before start changing the table.

**Comment by codenamerana** [comment]
Great,
I will try it for sure :)

Thanks for the help

On Wed, Dec 30, 2015 at 8:12 AM, Leonardo Zizzamia <notifications@github.com
