### ISSUE TITLE
Setting custom pagination template in Angular templates folder

### ISSUE THREAD

**Issue by chrisvel** [Zizzamia/ng-tasty#190]
Is there any way we could do this? The only thing I see to setup a custom .html file is setting the template with inline `<script>` tag which seems bad.. I would like to have a pagination.html file inside my Angular's templates folder (I am working in Rails fyi). Is that possible ?

**Comment by Zizzamia** [comment]
Did you read this http://zizzamia.com/ng-tasty/directive/table/custom-pagination `bind-template-url` ?

**Comment by chrisvel** [comment]
Obviously yes. Did I miss something ?

**Comment by Zizzamia** [comment]
You can set a custom template by using `bind-template-url` or `template-url` attribute.

**Comment by chrisvel** [comment]
Sorry, I am not sure you understand. In your example you have inline `<script></scvript>` code to set the template's url, by setting the id of the script as the `template-url`. I want to set the template as a file in the root of my project's folder, which is not happening. For example, there is an `angular-app` folder tree, with controllers, filters, directives and a `templates` folder with all my htmls. If I set the `template-url` to `../templates/my_pagination_template.html`, nothing changes.

**Comment by vidvid** [comment]
@chrisvel 
I am using this feature and it works well. Here is the code piece I use:

    <div tasty-pagination template-url="/assets/partials/table/pagination.html"></div>

Maybe you should recheck your url.

**Comment by Zizzamia** [comment]
Thanks @vidvid :+1:
