### ISSUE TITLE
sorting a client side table - case  snsetive

### ISSUE THREAD

**Issue by sali1982** [Zizzamia/ng-tasty#192]
I want to sort alphabetically not considering if it is capital or not.
How I can do it with ng-tasty?

**Comment by Zizzamia** [comment]
Angularjs orders it alphabetically case-insensitive. In JavaScript string comparison is case-sensitive.
Can you show me a case where is not working please.

**Comment by sali1982** [comment]
Sorry, That was my mistake. I should have closed this. It was sorting on something! I do not know on what...  issue was the header name was spelled wrong. It was sorting weirdly. I thought that is case  sensitive! :)

**Comment by Zizzamia** [comment]
Ok nice!!! Merry Christmas 🎄✨
