### ISSUE TITLE
Question: Will ng-tasty be supported in Angularjs 2?

### ISSUE THREAD

**Issue by sali1982** [Zizzamia/ng-tasty#201]
I am thinking of preparing for the conversion to Angularjs2.

Do you know if it is going to work with 2, or you need to publish a new version to work with it?

**Comment by Zizzamia** [comment]
Angular2 it's made it to support any kind of Angular1 library, needs ofcourse some trick to make it happen.

But to make things easily working, I will make probably in March/April ngTasty for Angular2.

**Comment by sali1982** [comment]
Great
