### ISSUE TITLE
Select rows

### ISSUE THREAD

**Issue by alfredobarron** [Zizzamia/ng-tasty#214]
There a way for select rows?, there a way for get selected rows?

**Comment by jvyang** [comment]
Assuming that the requirement is simple, I could probably do something like this:

**Markup**

``` html
<tr ng-repeat="row in rows" ng-click="selectedRows.push(row.foo)">
  <td>{{ row.foo }}</td>
  <td>{{ row.bar }}</td>
</tr>
```

**Controller**

``` javascript
$scope.selectedRows = [];
```

**Comment by alfredobarron** [comment]
Ok thanks, I thought it has some easier-automatic way to do it.
