### ISSUE TITLE
repo removed from google

### ISSUE THREAD

**Issue by gdi2290** [Zizzamia/ng-tasty#81]
https://www.chillingeffects.org/notices/10275257#infringing_url_598767486

**Comment by Zizzamia** [comment]
Why?

**Comment by Zizzamia** [comment]
Thank you for reporting this but, all of this has no sense!
And this motivation it's totally wrong.
"The materials reported in this notice are the copyrighted DVD/videos of Wicked Pictures. A representative list of these works is available at http://www.wickedpictures.com"

**Comment by Zizzamia** [comment]
https://github.com/Zizzamia/ng-tasty was not in Google during all yesterday, and now looks is back.

**Comment by gdi2290** [comment]
fill this out 
https://support.google.com/legal/contact/lr_counternotice?product=websearch

**Comment by Zizzamia** [comment]
ThankYou
