### ISSUE TITLE
Reloading Table data after JSON Response

### ISSUE THREAD

**Issue by vinsim24** [Zizzamia/ng-tasty#84]
Hi, I am using the ng-tasty sortable server side table in one of my projects. My question is:
I load a data table using the ng-tasty server side plugin.  Everything loads fine and sorting works perfectly by calling the getResource callback method with server side url, say A.

In that same table I have a column which has a link for each row and click of it should call a url say B(and take custom params) and the response of this url will be same JSON as url A which is needed by ngTasty table.

Please let know the way I need to bind the href in the table column and reload the updated data from service call.

**Comment by Zizzamia** [comment]
Hi @vinsim24, tomorrow I will make a plunker to better show you a complete solution.
For now I want show you a partial one.
Markup
```html
<div tasty-table bind-resource-callback="getResource" bind-filters="filterBy">
  <table class="table table-striped table-condensed">
    <thead tasty-thead></thead>
    <tbody>
      <tr ng-repeat="row in rows">
        <td>
           <a href ng-click="$scope.filterBy.name = row.name"  ng-bind="row.name"></a>
        </td>
        <td ng-bind="row.star"></td>
      </tr>
    </tbody>
  </table>
  <div tasty-pagination></div>
</div>
```
Javascript
```js
$scope.filterBy = {
  'name': ''
};
$scope.getResource = function (params, paramsObj) {
  var urlApi = 'table.json?' + params;
  return $http.get(urlApi).then(function (response) {
    return {
      'rows': response.data.rows,
      'header': response.data.header,
      'pagination': response.data.pagination,
      'sortBy': response.data['sort-by'],
      'sortOrder': response.data['sort-order']
    }
  });
}
```
Api url
```
table.json?sort-by=name&sort-order=dsc&page=1&count=5&name=....
```

So the idea is you can manipulate custom params by the object you passing inside `bind-filters`, maybe is not the correct name for a good API.
Probably need a better name, because is not just a filter object, in this case every key inside `$scope.filterBy` is going to be a custom params in your URL.
So that means you can play with that and make your custom B call.

Tomorrow I will make this example easy to understand by a plunker online demo.
Let me know if everything is clear. Or if you have more question about it.
ThankYou for open the issue,
ngTasty is a cool tool but need improvement on the documentation.

**Comment by vinsim24** [comment]
@Zizzamia I added the bind-filters and the custom attribute gets added to the API url.  Few more dots missing in this... Will explain the same:
1)Firstly I need to set 3 custom attributes with the content of row as shown below:

```html
<div tasty-table bind-resource-callback="getResource" bind-filters="filterBy">
  <table class="table table-striped table-condensed">
    <thead tasty-thead></thead>
    <tbody>
      <tr ng-repeat="row in rows">
        <td ng-bind="row.star"></td>
         <td>
            <a href ng-click="$scope.filterBy.A = row.A;$scope.filterBy.B = row.B;$scope.filterBy.C = row.C;">Cancel</a>
        </td>
      </tr>
    </tbody>
  </table>
</div>
```

```javascript
$scope.filterBy = {
  'A': '',
  'B': '',
  'C': '',
};
$scope.getResource = function (params, paramsObj) {
  var urlApi = 'table.json?' + params;
  return $http.get(urlApi).then(function (response) {
    return {
      'rows': response.data.rows,
      'header': response.data.header,
      'pagination': response.data.pagination,
      'sortBy': response.data['sort-by'],
      'sortOrder': response.data['sort-order']
    }
  });
}
```
Is the above approach to set filters right?
2)The page loaded correctly with data in table.
But when I click the cancel link it didnt call the server url and so the table never got reloaded. Is something needs to be added in ng-click so that server url is called and table gets reloaded with the filter data.

**Comment by Zizzamia** [comment]
The reason does not call the server url is because you just not assign correctly your `filterBy` variable.
In your template you don't need use `$scope` to access the AngularJS scope.
```html
// Wrong
<a href ng-click="$scope.filterBy.A = row.A;$scope.filterBy.B = row.B;$scope.filterBy.C = row.C;">Cancel</a>
```

Instead you should do in this way
```html
// Correct
<a href ng-click="filterBy.A = row.A; filterBy.B = row.B; filterBy.C = row.C;">Cancel</a>
```

This should fix your problem.
Please let me know if does work.

**Comment by vinsim24** [comment]
Suggested changes worked good.
Should be the last one, how do I reload the table on click of a button outside the table, without page being reloaded.

**Comment by Zizzamia** [comment]
What do you want reload exactly?

**Comment by vinsim24** [comment]
The entire content of the table as it would be loaded on page load.

**Comment by Zizzamia** [comment]
So if you want reset the table to the beginning content, you just need set `filterBy` empty as was in the beginning.
```js
$scope.filterBy = {
  'A': '',
  'B': '',
  'C': '',
};
```

**Comment by Zizzamia** [comment]
Hi @vinsim24 did you still have this problem?

**Comment by vinsim24** [comment]
Apologies, I forgot to update. All is good.

**Comment by Zizzamia** [comment]
#ThankYou
