### ISSUE TITLE
Empty initialization

### ISSUE THREAD

**Issue by vhmolinar** [Zizzamia/ng-tasty#88]
What would be the best way to initialize tasty-table without data filled in table?
I found myself doing workaround to make it possible.
My scenario is just as follows:

- I have a table with headers set
- I will fill that once user clicks a search button
- The data will be paginated

this is how I set the table
```html
<div tasty-table bind-resource-callback="getResource" bind-init="pagination">
  <table class="app-grid table table-striped table-condensed">
    <thead>
        <tr>
            <th ng-repeat="filter in filters">
                {{filter.label}}
            </th>
        </tr>
    </thead>
    <tbody>
      <tr ng-repeat="row in rows track by $index">
          <td ng-repeat="column in row track by $index">
              {{column}}
          </td>
      </tr>
    </tbody>
  </table>
  <div tasty-pagination></div>
</div>           
```

Problems found so far:
- The directive tries to fetch data throught getResource at initialization. But I'd like to only query for it when user perform the search
- If I workaround getResource method to return an empty promise at initialization time, then it also wont solve the problem. Since rows property wont be hit after the manual search.

I know it sounds newbie. But I havent found many options at http://zizzamia.com/ng-tasty/ . Sorry if I missunterstood something. Any help?

Regards

**Comment by Zizzamia** [comment]
ThankYou for sharing your experience with ngTasty.
I never thought about your specific case, I believe the best implementation should be have the object `bind-init` as default `false`, in this way does not fetch data in the beginning.
And only if you set `bind-init="init"` equal to something like `$scope.init = { 'count': 5 };` will start ad default with that values.

So in the end, I will make a ticket and implement this case in the next version of ng-tasty.
Really thank you to reporting this case.
