### ISSUE TITLE
Can't init custom count value in first request (server side).

### ISSUE THREAD

**Issue by effectidea** [Zizzamia/ng-tasty#91]
Use case:

In controller:  
`$scope.initTasty = {
            'count': 20,
            'page': 1
        };`

In view:
`<div tasty-table bind-resource-callback="getActivityReport" bind-init='initTasty' bind-filters="filterBy">`

In log:
`count=5&date-range=quarter&page=1`

5 is not 20  :)

In debugger:
tastyTable scope: url = `page=1&count=5&date-range=quarter`

Thanks.

**Comment by Zizzamia** [comment]
ThankYou to reporting this bug, I will take care of this during weekend.
