### ISSUE TITLE
Table does not display after API call

### ISSUE THREAD

**Issue by jvjvjv** [Zizzamia/ng-tasty#92]
I have a case where I cannot use `bind-resource-callback` in my table, as I only wish to call data from the server once. So my page is set up using the regular _Table_ example, except instead of a static table in the controller, I make an API call. The data does not display until I click on a column to change sorting. I hope you can help. I've tried to rewrite the code below instead of copy/paste, but if I introduced any syntax or other errors I apologise. 

I'm still using 0.4.6. If an update will fix this please let me know.

#### HTML
```html
<div tasty-table bind-resource="resource">
  <table class="table table-striped table-condensed">
    <thead tasty-thead bind-not-sort-by="notSortBy"></thead>
      <tbody>
        <tr ng-repeat="row in rows">
          <td ng-bind="row.name"></td>
          <td ng-bind="row.address"></td>
          <td>
            <div ng-repeat="user in row.users" ng-bind="user.manager.first_name + ' ' +user.manager.last_name"></div>
          </td>
      </tr>
    </tbody>
  </table>
</div>
```
#### Javascript
```javascript
$scope.notSortBy = ['users'];
$scope.resource = {
  "header": [
    {"key": "name", "name": "Location", "style": {"width": "25%"}},
    {"key": "address", "name": "Address", "style": {"width": "25%"}},
    {"key": "users", "name": "Users", "style": {"width": "50%"}},
  ],
  "rows": [],
  "sortBy": "name",
  "sortOrder": "asc"
};
$http.get('/api/users')
  .success(function (data) {
      var rows = [];
      var locations = data;
      for (var i = 0; i < locations.length; i++) {
        var obj = {
            'name': locations[i].location_name,
            'address': locations[i].address1, 
            'users': locations[i].locationManagers
          };
          rows.push(obj);
        }
      $scope.resource.rows = rows;
    }
);
```

**Comment by Zizzamia** [comment]
My first advice, is too update `ng-tasty` to the latest version `0.4.7`, also I will try to replicate your case in the documentation.
ThankYou for ask the question

**Comment by Zizzamia** [comment]
Here the documentation to implement sorting/pagination table client side and loading the resource by `$http`.
http://zizzamia.com/ng-tasty/directive/table/simple-http

Please let me know if the docs is enough clear, and solve your case :)
Thank you again

**Comment by cadooo** [comment]
You need to add watch-resource="collection".

http://zizzamia.com/ng-tasty/directive/table/simple-http
watch-resource="collection"
The main difference between the Table simple and Table simple $http is the initialization time of the resource in the table. In this case we start with $scope.resource.rows = [] and only after the http request we populate that value. As default the table is updated only if the reference of the resource variable is changed. To update in this case we need to change the $watch resource from reference to collection.

**Comment by Zizzamia** [comment]
Hi @jvjvjv did you still have this problem?

**Comment by Zizzamia** [comment]
Looks this issue it's complete by the new docs, if is still a problem please let me know guys.
