### ISSUE TITLE
Have possible use the full options of bind-filters

### ISSUE THREAD

**Issue by Zizzamia** [Zizzamia/ng-tasty#94]
By passing filters, we want also use the full power of filter `filter`.
https://docs.angularjs.org/api/ng/filter/filter

**Comment by p1lare** [comment]
I cannot get the functionality in ngTasty to use field specific filters with general search in the same time, as presented in angular documentation.

[https://docs.angularjs.org/api/ng/filter/filter](url)

```
<label>Any: <input ng-model="search.$"></label> <br>
<label>Name only <input ng-model="search.name"></label><br>
<label>Phone only <input ng-model="search.phone"></label><br>
```

With ngTasty I can only submit one filter which will work as general one when I will pass string, and field specific when I will pass an object with those fields names as above.
