### ISSUE TITLE
Pagination must be reset after new filter

### ISSUE THREAD

**Issue by sazary** [Zizzamia/ng-tasty#98]
Hi
these are the steps to reproduce this bug:  
1. go to page n >= 2
2. change a filter criteria, so that the resulting data comes in less pages than n. for example go to page 5, then search for something that has less than 5 pages of data. then table doesn't show anything, but it must show.

how to fix the bug:
reset pagination to page 1 after every change in filters.

**Comment by Zizzamia** [comment]
Are you using #ngTasty version 0.5.0 ? This looks an old bug already fix few months ago.

**Comment by sazary** [comment]
yes it is 0.5.0

**Comment by Zizzamia** [comment]
What table are we talking about: 
Table client side
```html
<div tasty-table bind-resource="resource"> ... </div>
```

Table server side
```html
<div tasty-table bind-resource-callback="getResource" bind-init="init" bind-filters="filterBy"> ... </div>
```

I try to replicate the error on the docs, but was not possible.

**Comment by sazary** [comment]
I'm talking about server side one. follow these steps to reproduce the bug:
1. go to [this page](http://zizzamia.com/ng-tasty/directive/table-server-side).
2. search for "s".
3. go to page 3.
4. now search for "bar".
5. note that number of pages in pagination bar reduces to one page, but no item is shown in the table. also note that in the API URL, the page requested is `page=3`.
6. now click on page one in the pagination bar. items appear.
I hope that this helps.

**Comment by Zizzamia** [comment]
#ThankYou @sazary to report this issue, was really helpful! 
In the next release will be out this fix.

**Comment by sazary** [comment]
Thank you for fixing it!

**Comment by thesilverbadger** [comment]
I'm not sure that this has been fixed, as we're running into the same issue (using 0.5.5), and I can repro on the [Table with reload callback](http://zizzamia.com/ng-tasty/directive/table-server-side/reload) page.

1. Click Page 5
2. Enter "cup" in filters by name.
3. Click Search.

The params string doesn't reset the page to 0, instead leaves it at 
[sort-by=name&sort-order=dsc&page=5&count=5&name=cup]

I would expect this to reset the page to 0 (as effectively the user is starting from scratch).

**Comment by Zizzamia** [comment]
Hey @thesilverbadger your problem was fix in the https://github.com/Zizzamia/ng-tasty/issues/142 issue.
And if you update #ngTasty to the version 0.5.6 you will get the fix.
Please let me know if you still have problem.

**Comment by javi-more-garc** [comment]
Hi there,

I think the issue may still be present in the latest version 0.5.8.

We can test it this way:

1) Navigate to http://zizzamia.com/ng-tasty/directive/table-server-side/complete 
2) Clear the "r" from the filters (by name)
3) Click on page number 5
4) Introduce "cup" in the filters (by name)

There is a result but it is not shown (I am attaching a snapshot of the problem). If we click on the page number 1 everything would be fine.

![image](https://cloud.githubusercontent.com/assets/2869838/10619015/9a7eebe2-7773-11e5-811a-e5b0d50e93ec.png)

Regards,

Javi

**Comment by Zizzamia** [comment]
Hi @javi-more-garc thanks to report the bug,
the docs were not update with the latest version on ngTasty,
http://zizzamia.com/ng-tasty/directive/table-server-side/complete

Just fix that :-)

**Comment by javi-more-garc** [comment]
Hi, 

thank you for your response.

My implementation does not rely on a front-end filter but rather performs a search and the server returns all results sorted/ filtered.

The behavior is analogous: say I search and get 15 results. I click on the second page and search again using a more restrictive filter. The server returns 6 results this time but there are no rows shown even when I can see there is a page:

![image](https://cloud.githubusercontent.com/assets/2869838/10777605/709891f2-7d1d-11e5-8ab2-51065c479b7d.png)

Even the footer is right: "Page 1 of 1, of 6 entries" but there are no rows. If I click on the page (1) everything is fine (i.e. rows are displayed)

Is there any way to sort of reset everything (current page, sorting..) so that the new results from a search are displayed as if it was the first time? 

Thank you,

Javier

**Comment by Zizzamia** [comment]
@javi-more-garc can you please open a new issue about this error. :-)
Thanks
